import type { Metadata } from "next";
import { headers } from "next/headers";
import "@/styles/globals.css";
import { RenewSession } from "@/components/renewSession";
export const metadata: Metadata = {
  title: "Create Management App (Frontend)",
  description: "Generated by ExceSoft",
};
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/hooks/authContext";

export default async function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {

  const header = await headers();
  const userHeader = header.get('user');
  const user = userHeader ? JSON.parse(userHeader) : null;
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <AuthProvider initialUser={user}>
            <RenewSession exp={user?.exp} />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
